name: GitHub Build Pipeline
on:
    push:
        tags:
          - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
    build_release:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code to Build
          uses: actions/checkout@v3
        - name: Setup Go
          uses: actions/setup-go@v3
          with:
            go-version: '1.18'
        - name: Run x64 build
          run: go build -o gotcpscan-x64 main.go
          env:
              GOOS: linux
              GOARCH: 'amd64'
        - name: Run x86 build
          run: go build -o gotcpscan-x86 main.go
          env:
              GOOS: linux
              GOARCH: '386'
        - id: Release
          uses: softprops/action-gh-release@v1
          with:
              files: |
                gotcpscan-x86
                gotcpscan-x64
